// export const CHANGE_CONNECTION_STATUS = 'CHANGE_CONNECTION_STATUS';
// export const SET_USER = 'SET_USER';

export const LOADING = 'LOADING';
export const END_LOADING = 'END_LOADING';
export const ERROR = 'ERROR';
export const FB_LOGIN = 'FB_LOGIN';
export const FB_LOGOUT = 'FB_LOGOUT';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SHOW_TOAST = 'SHOW_TOAST';
export const CLOSE_TOAST = 'CLOSE_TOAST';
export const SET_USER = 'SET_USER';
export const SET_THEME = 'SET_THEME';

export const SET_CART = 'SET_CART';
export const RESET_CART = 'RESET_CART';

export const UNREAD_MESSAGES = 'UNREAD_MESSAGES';

//academic
export const ADD_COURSE = 'ADD_COURSE';
export const REMOVE_COURSE = 'REMOVE_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';

export const ADD_EXAM = 'ADD_EXAM';
export const REMOVE_EXAM = 'REMOVE_EXAM';
export const UPDATE_EXAM_STATUS = 'UPDATE_EXAM_STATUS';
export const OPEN_ACADEMIC_MODAL = 'OPEN_ACADEMIC_MODAL';
export const CLOSE_ACADEMIC_MODAL = 'CLOSE_ACADEMIC_MODAL';
export const ACADEMIC_ERROR = 'ACADEMIC_ERROR';

//professional
export const ADD_COMPANY = 'ADD_COMPANY';
export const REMOVE_COMPANY = 'REMOVE_COMPANY';
export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const OPEN_COMPANY_MODAL = 'OPEN_COMPANY_MODAL';
export const CLOSE_COMPANY_MODAL = 'CLOSE_COMPANY_MODAL';
export const COMPANY_ERROR = 'COMPANY_ERROR';

export const CHANGE_CONNECTION_STATUS = 'CHANGE_CONNECTION_STATUS';
export const INITIALIZE_COURSES = 'INITIALIZE_COURSES';
export const SHOW_ERROR_ALERT = 'SHOW_ERROR_ALERT';
export const CLOSE_ERROR_ALERT = 'CLOSE_ERROR_ALERT';
export const TOGGLE_ERROR_ALERT = 'TOGGLE_ERROR_ALERT';
export const INITIALIZE_COMPANIES = 'INITIALIZE_COMPANIES';

export const TOGGLE_SNACKBAR = 'TOGGLE_SNACKBAR';

export const UTILITIES_ALL = 'UTILITIES_ALL';
export const CMS_DATA = 'CMS_DATA';

export const CATEGORIES_ALL = 'CATEGORIES_ALL';

export const LOCALSTORAGE_USER_DATA = 'USER_DATA';
export const ACCESS_TOKEN = 'ACCESS_TOKEN';
export const THEME = 'THEME';
export const USER_ROLE = 'USER_ROLE';
